name: Manual Deployment

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
workflows:
  custom:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Manual Deployment
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const { data } = await octokit.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: 'manual-deployment.yml',
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
